### ISSUE TITLE
Breaks messenger.com

### ISSUE THREAD

**Issue by leo-liar** [gorhill/uBO-Extra#25]
This maybe similar to cjmalloy's issue.

With this extension enabled it's impossible to establish video/audio chat connections on Facebook's "messenger.com". When trying to call someone anduBlock Extra is active Chrome's dev console gives the following error:

`Refused to connect to 'wss://www.messenger.com/' because it violates the following Content Security Policy directive: "connect-src *.facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* *.akamaihd.net wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* *.atlassolutions.com attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm *.messenger.com".`

When accessing the messenger via the facebook.com website, there's no problem at all to initiate or receive calls with or without the extension enabled.
(By the way uBlock's "Prevent WebRTC from leaking local IP address" setting doesn't affect this matter at all.)

I'm on Win 8.1 x64 using Chrome 56.0.2924.87 x64.

**Comment by gorhill** [comment]
Can you confirm the issue is fixed with 2.9?

**Comment by leo-liar** [comment]
Yes, calling now works while uBlock Extra is enabled. Thanks for the quick fix!

**Comment by bobsage123** [comment]
I think there may be an issue with messanger and ubo extra again. Possibly due to Facebook making use of instart logic? When using messanger on Facebook and typing, my cursor will constantly jump to the front of my sentance, causing what I'm typing to be all screwed up. Almost like something is taking away the focus of the chat. Oddly, and this is the same behavior instart exhibits, as soon as I open up the ublock origin logger, the issue completley ceases.
