### ISSUE TITLE
Not blocked websockets (worker, frame)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBO-Extra#8]
Google Chrome 53.0.2785.89 m (64-bit)
uBO 1.9.4, uBlock Origin WebSocket 1.1
http://hdrezka.me/films/action/11147-dedpul.html
http://i.imgur.com/Gigexom.jpg

http://filmix.net/
http://i.imgur.com/JJIxJC3.jpg

**Comment by gorhill** [comment]
Also: <https://github.com/gorhill/uBlock/issues/1936>.

**Comment by ImCatzilla** [comment]
Similar issue here:
http://seasonvar.ru/serial-13723-Poslednij_korabl_-3-season.html
Teasers in left sidebar.

Websockets connection code was wrapped into:
`new Worker(URL.createObjectURL(new Blob(['eval(atob(" ... Base64 Encoded script ... "))']), {type: "application/javascript"}));`

Filter, which does not work as expected:
`||marketgid.com^`

Reproducible on:
Chromium 52.0.2743.116, Debian 8.5 (64-bit)
uBlock Origin 1.9.10
uBlock Origin WebSocket 1.1

**Comment by gorhill** [comment]
> Similar issue here:
> http://seasonvar.ru/serial-13723-Poslednij_korabl_-3-season.html
> Teasers in left sidebar.

Works fine with default filter lists. Did you disable any of these default filter lists?

**Comment by ImCatzilla** [comment]
> Did you disable any of these default filter lists?

Yes, I use only my own filter list, located here:
https://www.dropbox.com/s/gufsjlap8kphzk7/ads.txt?dl=1

I confirm, this problem does not occur when I using the default filters. But they also hide the sidebar. Maybe websocket connection does not appear because sidebar is hidden.

If I disable default filters, site successfully establishes a connection with the following websocket:
`wss://wsp.marketgid.com/ws`

But it should be blocked by the following rule in my filter list:
`||marketgid.com^`

Previously this rule blocks websocket on this site. But yesterday they changed the teasers code.

**Comment by gorhill** [comment]
> Yes, I use only my own filter list

Use this in your filter list: `*$websocket,seasonvar.ru`.

**Comment by ImCatzilla** [comment]
> Use this in your filter list

Thanks a lot, it works. I am sorry for disturbing.
